spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/metroDB
    username: metro
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:liquibase/changelog.yml
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: full


