-- liquibase formatted sql

-- changeset ymalykh:1

CREATE TABLE IF NOT EXISTS routes
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(15) NOT NULL UNIQUE,
    name varchar(150) NOT NULL UNIQUE
);

